function(TARGET_CONFIGURE_SETUP tgt_symbol tgt_name)
    set(MODULE_NAME ${tgt_name} PARENT_SCOPE)
    set(MODULE_NAME ${tgt_name})
    target_compile_definitions(${tgt_symbol} PRIVATE -DMACHI_${MODULE_NAME})
    set(lower_tgt_name)
    string(TOLOWER ${tgt_name} lower_tgt_name)
    configure_file(${PROJECT_SOURCE_DIR}/cmakes/config.h.in ${CMAKE_CURRENT_SOURCE_DIR}/${lower_tgt_name}_config.h @ONLY)
    message("$add config fille to ${tgt_name} : [ loc : ${CMAKE_CURRENT_BINARY_DIR} ]")
    message("mudule name : ${MODULE_NAME}/${tgt_name}")
    target_include_directories(${tgt_symbol} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
endfunction()